name: Build

on: [push, pull_request]

jobs:
  build_addon:
    name: Build Blender ZIP add-on
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Setup Poetry plugins
        run: poetry self add poetry-plugin-export
      - name: Build add-on
        run: etc/scripts/create_blender_dist.sh
      - uses: actions/upload-artifact@v4
        with:
          name: skybrush-studio-blender
          path: ./dist/*.zip
